import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Posts from "./posts/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Sidebar />
        <div className="flex  ml-64 w-full">
          <div className=" min-h-screen max-w-[900px] flex-1 border-r border-r-skyBlue/50 ">
            {children}
          </div>
          {/* <Posts /> */}
        </div>
      </body>
    </html>
  );
}
